version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    container_name: node_app
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    networks:
      - app_network
  postgres:
    image: postgres:latest
    container_name: postgres_court_reservation
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: court_reservation
      POSTGRES_USER: court_reservation
      POSTGRES_PASSWORD: court_reservation
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
networks:
  app_network:
    driver: bridge
